//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// SwaySensor.rc で使用
//
#define IDC_MYICON                      2
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_SWAYSENSOR                  107
#define IDI_SMALL                       108
#define IDC_SWAYSENSOR                  109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_TASKSET              129
#define IDB_BMP_AGENT                   143
#define IDB_BMP_BLUE                    144
#define IDB_BMP_ENVIRONMENT             145
#define IDB_BMP_GRAY                    146
#define IDB_BMP_GREEN                   147
#define IDB_BMP_LIGHTBLUE               148
#define IDB_BMP_MAGENTA                 149
#define IDB_BMP_POLICY                  150
#define IDB_BMP_RED                     151
#define IDB_BMP_SCADA                   152
#define IDB_BMP_WHITE                   153
#define IDB_BMP_YELLOW                  154
#define IDD_DIALOG_IMAGE_PROC           155
#define IDC_LIST                        1000
#define IDC_STATIC_TITLE_IMAGE          1000
#define IDC_STATIC_TASKNAME             1001
#define IDC_STATIC_TITLE_TAGET_POS      1002
#define IDC_STATIC_TARGET_1             1003
#define IDC_STATIC_TARGET_2             1004
#define IDC_RADIO_TASK_FUNC1            1005
#define IDC_STATIC_TITLE_SWAY_SENSOR_INFO 1005
#define IDC_RADIO_TASK_FUNC2            1006
#define IDC_STATIC_TITLE_TILT           1006
#define IDC_RADIO_TASK_FUNC3            1007
#define IDC_STATIC_TITLE_TILT_SPD       1007
#define IDC_RADIO_TASK_FUNC4            1008
#define IDC_RADIO_TASK_FUNC5            1009
#define IDC_RADIO_TASK_FUNC6            1010
#define IDC_STATIC_TITLE_H              1011
#define IDC_SLIDER_H1_LOW               1013
#define IDC_STATIC_TITLE_IMG_GRAB_TIME  1014
#define IDC_STATIC_VAL_H1_LOW           1015
#define IDC_SLIDER_H1_UPP               1016
#define IDC_STATIC_VAL_H1_UPP           1017
#define IDC_SLIDER_S1_LOW               1018
#define IDC_STATIC_TASKNAME_TITLE       1019
#define IDC_STATIC_TITLE_S              1019
#define IDC_STATIC_VAL_S1_LOW           1020
#define IDC_SLIDER_S1_UPP               1021
#define IDC_STATIC_VAL_S1_UPP           1022
#define IDC_SLIDER_V1_LOW               1023
#define IDC_STATIC_TITLE_V              1024
#define IDC_STATIC_VAL_V1_LOW           1025
#define IDC_SLIDER_V1_UPP               1026
#define IDC_STATIC_VAL_V1_UPP           1027
#define IDC_SLIDER_H2_LOW               1028
#define IDC_STATIC_VAL_H2_LOW           1030
#define IDC_STATIC_TITLE_IMAGE_STAT     1031
#define IDC_SLIDER_H2_UPP               1032
#define IDC_STATIC_VAL_H2_UPP           1033
#define IDC_SLIDER_S2_LOW               1034
#define IDC_STATIC_VAL_S2_LOW           1036
#define IDC_SLIDER_S2_UPP               1037
#define IDC_STATIC_VAL_S2_UPP           1038
#define IDC_SLIDER_V2_LOW               1039
#define IDC_STATIC_VAL_V2_LOW           1041
#define IDC_SLIDER_V2_UPP               1042
#define IDC_STATIC_VAL_V2_UPP           1043
#define IDC_STATIC_TITLE_NOISEFILTER    1046
#define IDC_SLIDER_NOISEFILTER1         1047
#define IDC_STATIC_VAL_NOISEFILTER1     1048
#define IDC_COMBO_NOISEFILTER1          1049
#define IDC_CHECK_CURSOR                1050
#define IDC_CHECK_ROI                   1051
#define IDC_COMBO_NOISEFILTER2          1052
#define IDC_COMBO_IMAGE                 1053
#define IDC_SLIDER_NOISEFILTER2         1054
#define IDC_STATIC_TITLE_CAMERA_EXPOSURE 1055
#define IDC_STATIC_VAL_NOISEFILTER2     1056
#define IDC_STATIC_TITLE_TILT_STAT      1058
#define IDC_SLIDER_CAMERA_EXPOSURE      1059
#define IDC_STATIC_VAL_CAMERA_EXPOSURE  1060
#define IDC_SLIDER_TARGET_LEN           1061
#define IDC_STATIC_TARGET_POS_X_1       1062
#define IDC_STATIC_TARGET_POS_X_2       1063
#define IDC_STATIC_TARGET_POS_Y_1       1064
#define IDC_STATIC_TARGET_POS_Y_2       1065
#define IDC_STATIC_TILT_DEG_X           1068
#define IDC_STATIC_TILT_DEG_Y           1069
#define IDC_STATIC_TILT_RAD_X           1070
#define IDC_STATIC_TILT_RAD_Y           1071
#define IDC_STATIC_IMG_GRAB_TIME        1072
#define IDC_STATIC_VAL_TARGET_LEN       1073
#define IDC_STATIC_IMAGE_STAT           1074
#define IDC_STATIC_TILT_STAT            1075
#define IDC_STATIC_TILT_SPD_DEG_X       1076
#define IDC_STATIC_TITLE_SWAY           1077
#define IDC_STATIC_SWAY_X               1078
#define IDC_STATIC_SWAY_Y               1079
#define IDC_STATIC_TITLE_SWAY_SPD       1080
#define IDC_STATIC_SWAY_SPD_X           1081
#define IDC_STATIC_SWAY_SPD_Y           1082
#define IDC_STATIC_TITLE_SWAY_ZERO      1083
#define IDC_SCROLLBAR_IMAGE_H           1084
#define IDC_SCROLLBAR_IMAGE_V           1085
#define IDC_STATIC_SWAY_ZERO_X          1086
#define IDC_STATIC_SWAY_ZERO_Y          1087
#define IDC_CHECK_IMAGE_SCALE           1088
#define IDC_STATIC_TILT_SPD_DEG_Y       1089
#define IDC_CHECK_TARGET_ROI_1          1090
#define IDC_CHECK_TARGET_POS_1          1091
#define IDC_CHECK_TARGET_CONTOURS_1     1092
#define IDC_CHECK_TARGET_ROI_2          1093
#define IDC_CHECK_TARGET_POS_2          1094
#define IDC_CHECK_CAMERA_EXPOSURE       1095
#define IDC_CHECK_TARGET_LEN            1096
#define IDC_CHECK_TARGET_CONTOURS_2     1097
#define IDC_STATIC_TITLE_IMAGE_MASK     1098
#define IDC_STATIC_TITLE_TARGET_LEN     1099
#define IDC_BUTTON_TASK_ITEM1           1100
#define IDC_STATIC_TILT_SPD_RAD_X       1100
#define IDC_BUTTON_TASK_ITEM2           1101
#define IDC_CHECK_SWAY_POS              1101
#define IDC_BUTTON_TASK_ITEM3           1102
#define IDC_STATIC_TILT_SPD_RAD_Y       1102
#define IDC_BUTTON_TASK_ITEM4           1103
#define IDC_BUTTON_TASK_ITEM5           1104
#define IDC_BUTTON_TASK_ITEM6           1105
#define IDC_BUTTON_CURSOR_L             2028
#define IDC_BUTTON_CURSOR_R             2032
#define IDC_BUTTON_CURSOR_U             2033
#define IDC_BUTTON_CURSOR_D             2034
#define IDC_BUTTON_IMAGE_SAVE           2041
#define IDC_STATIC_BMP_IMAGE            2045
#define IDC_STATIC_BMP_TARGET_2         2047
#define IDC_STATIC_BMP_SWAY_POS         2048
#define IDC_STATIC_BMP_TARGET_1         2049
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
